this is my yaml:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lowco2-keycloak
  labels:
    app: lowco2-keycloak
  namespace: student-f-jungwirth1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lowco2-keycloak
  template:
    metadata:
      labels:
        app: lowco2-keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0.7
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "reencrypt"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KC_HOSTNAME_ADMIN_URL
              value: "https://student.cloud.htl-leonding.ac.at/lowco2-keycloak/"
            - name: KC_HOSTNAME_STRICTw
              value: "false"
            - name: KEYCLOAK_FRONTEND_URL
              value: "https://student.cloud.htl-leonding.ac.at/lowco2-keycloak/auth"
            - name: REDIRECT_URL
              value: "https://student.cloud.htl-leonding.ac.at/lowco2-keycloak/"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "true"
            - name: HTTP_ENABLED
              value: "false"
          ports:
            - name: https
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lowco2-service-keycloak
  namespace: student-f-jungwirth1
spec:
  selector:
    app: lowco2-keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lowco2-keycloak-ingress
  namespace: student-f-jungwirth1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Forwarded-For $http_x_forwarded_for";
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /lowco2-keycloak/(.*)$
            pathType: Prefix
            backend:
              service:
                name: lowco2-service-keycloak
                port:
                  number: 8080