apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-01-13T10:58:21Z"
  name: student-f-jungwirth1
  resourceVersion: "121064080"
  uid: 8ae4520d-c25c-4b85-8617-ebffe716d0e3
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
