name: Deployment

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: floaterd2201/lowco2

jobs:
  release: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Create Release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: lowco-back/lowco2.yml
            tag: latest
            release_name: Release ${{ github.run_number }}
            overwrite: true 

  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd lowco-back
          docker build -t floaterd2201/lowco2 .

      - name: Login into Docker
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push latest to Docker
        run: docker push floaterd2201/lowco2:latest     

  electron:
      runs-on: ${{ matrix.os }}
  
      strategy:
        matrix:
          os: [windows-latest, macos-latest] 
        
      steps:
        - name: Checkout Repo
          if: startsWith(matrix.os, 'windows-latest')
          uses: actions/checkout@v3
  
        - name: Use Node.js
          if: startsWith(matrix.os, 'windows-latest')
          uses: actions/setup-node@v3
          with:
            node-version: 20
          
        - name: Run electron on windows  
          if: startsWith(matrix.os, 'windows-latest')
          run: |
              cd lowco-front
              npm i
              npm run build
              npm run electron:make-windows

        - name: Upload Windows file
          if: startsWith(matrix.os, 'windows-latest')
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: lowco-front/out/make/squirrel.windows/x64/lowco2-0.0.1 Setup.exe
            tag: latest
            overwrite: true
            prerelease: true

        - name: Checkout Repo
          if: startsWith(matrix.os, 'macos-latest')
          uses: actions/checkout@v3
  
        - name: Use Node.js
          if: startsWith(matrix.os, 'macos-latest')
          uses: actions/setup-node@v3
          with:
            node-version: 20

        - name: Run electron on mac  
          if: startsWith(matrix.os, 'macos-latest')
          run: |
              cd lowco-front
              npm i
              npm run build
              npm run electron:make-mac

        - name: Upload Mac file
          if: startsWith(matrix.os, 'macos-latest')
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: lowco-front/out/make/zip/darwin/arm64/lowco2-darwin-arm64-0.0.1.zip
            tag: latest
            overwrite: true
            prerelease: true
