name: Deployment

on:
  push:
    branches:
      - 'main'

env:
  DOCKER_HUB_USERNAME: ${{DOCKERHUB_USERNAME}}
  DOCKER_HUB_ACCESS_TOKEN: ${{DOCKERHUB_TOKEN}}
  IMAGE_NAME: floaterd2201/lowco2

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd lowco2/lowco-back
          docker build -t floaterd2201/lowco2

      - name: Login into Docker
        run: docker login -u ${{DOCKER_HUB_USERNAME}} -p ${{DOCKER_HUB_ACCESS_TOKEN}}

      - name: Push latest to Docker
        run: docker push floaterd2201/lowco2:latest
