name: Deployment

on:
  push:
    branches:
      - 'new-backend'

env:
  IMAGE_NAME: floaterd2201/lowco2
  REGISTRY: ghcr.io
  PROJECT_VERSION: latest
  ORG_ACTOR: 2223-4ahitm-project-lowco
  USER: florian-jungwirth
  PROJECT_NAME: lowco2

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: lowco-back/lowco2.yml
          tag: v0.0.${{github.run_number}}
          release_name: Release v0.0.${{github.run_number}}
          overwrite: true

  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUBTOKEN }}

      - name: Build
        run: |
          cd lowco-backend-neu/lowco-backend
          ./mvnw package
          docker build -f src/main/docker/Dockerfile.jvm -t floaterd2201/lowco2_neu .
          docker image tag floaterd2201/lowco2_neu ghcr.io/florian-jungwirth/lowco2_neu:latest
          docker image ls

      - name: Push latest to packages
        run: docker push ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}

      - name: Tag latest to date
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.PROJECT_NAME }} ${{ env.REGISTRY }}/${{ env.ORG_ACTOR }}/${{ env.PROJECT_NAME }}:$(date --rfc-3339=date)
          docker image ls

      - name: Push tagged version to packages
        run: docker push ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}