name: Deployment

on:
  push:
    branches:
      - 'test/nodeCache'

env:
  IMAGE_NAME: floaterd2201/lowco2

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: lowco-back/lowco2.yml
          tag: v0.0.${{github.run_number}}
          release_name: Release v0.0.${{github.run_number}}
          overwrite: true

  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd lowco-back
          docker build -t floaterd2201/lowco2 .

      - name: Login into Docker
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push latest to Docker
        run: docker push floaterd2201/lowco2:latest

  electron:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3.3.2
        with:
          path: |
            lowco-front/package-lock.json
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: lowco-front/package-lock.json

      

  apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          cd lowco-front
          npm install

      - name: Build Angular Ionic Project
        run: |
          cd lowco-front
          npm install -g @angular/cli  
          npm run build

      - name: Build APK
        run: |
          cd lowco-front
           npm install -g @ionic/cli  
          
           npm install -g @capacitor/cli 
          
           npm i @capacitor/core
          
           ionic capacitor build android
          
           ionic capacitor copy android
          
           cd android
          
           chmod +x ./gradlew
          
           ./gradlew assembleDebug

      - name: Upload APK file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./lowco-front/android/app/build/outputs/apk/debug/app-debug.apk
          tag: v0.0.${{github.run_number}}
          overwrite: true
          prerelease: true