name: Deployment

on:
  push:
    branches:
      - 'test/nodeCache'

env:
  IMAGE_NAME: floaterd2201/lowco2

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: lowco-back/lowco2.yml
          tag: v0.0.${{github.run_number}}
          release_name: Release v0.0.${{github.run_number}}
          overwrite: true

  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd lowco-back
          docker build -t floaterd2201/lowco2 .

      - name: Login into Docker
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push latest to Docker
        run: docker push floaterd2201/lowco2:latest

  electron:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3.3.2
        with:
          path: |
            lowco-front/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: lowco-front/package-lock.json

      - name: Run electron on windows
        if: startsWith(matrix.os, 'windows-latest')
        run: |
          cd lowco-front
          npm i
          npm run build
          npm run electron:make-windows

      - name: Upload Windows file
        if: startsWith(matrix.os, 'windows-latest')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: lowco-front/out/make/squirrel.windows/x64/lowco2-0.0.1 Setup.exe
          tag: v0.0.${{github.run_number}}
          asset_name: lowco2-windows-setup.exe
          overwrite: true
          prerelease: true

      - name: Run electron on mac
        if: startsWith(matrix.os, 'macos-latest')
        run: |
          cd lowco-front
          npm i
          npm run build
          npm run electron:make-mac

      - name: Upload Mac file
        if: startsWith(matrix.os, 'macos-latest')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: lowco-front/out/make/zip/darwin/arm64/lowco2-darwin-arm64-0.0.1.zip
          tag: v0.0.${{github.run_number}}
          asset_name: lowco2-mac.zip
          overwrite: true
          prerelease: true

  apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v3.3.2
        with:
          path: |
            lowco-front/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          cd lowco-front
          npm install

