name: Deployment

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: floaterd2201/lowco2

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd lowco-back
          docker build -t floaterd2201/lowco2 .

      - name: Login into Docker
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Push latest to Docker
        run: docker push floaterd2201/lowco2:latest
