name: release 

on:
  push:
    branches:
      - 'main'

jobs:
  release:
      runs-on: ${{ matrix.os }}
  
      strategy:
        matrix:
          os: [macos-latest, windows-latest] 
        
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v3
  
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 20
          
        - name: Run electron on windows  
          if: startsWith(matrix.os, 'windows-latest')
          run: |
              cd lowco-front
              npm run electron:make-windows
  
        - name: Run electron on mac  
          if: startsWith(matrix.os, 'macos-latest')
          run: |
              cd lowco-front
              npm run electron:make-mac
        
        - name: Create Release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: lowco-front/out/make/zip/darwin/arm64/lowco2-darwin-arm64-0.0.1.zip
            tag: latest
            release_name: Release ${{ github.event.repository.updated_at }}
            overwrite: true
  
        - name: Upload Kubernetes File
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: lowco-front/out/make/squirrel.windows/x64/lowco2-0.0.1 Setup.exe
            tag: latest
            overwrite: true
            prerelease: true
